apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: objectdetect-release010-test 
  janus-idp.io/tekton: objectdetect-release010-test
  backstage.io/kubernetes-id: objectdetect-release010-test
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: objectdetect-release010-test
resources: 
- application-dev.yaml