apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: objectdetect-release010-test
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/objectdetect-release010-test:880603453513bc2ac0a4267f716dc1cb3b266196@sha256:aa87b88cfcc9f303ad1e1c4d8173d6b93686b0e2b66aefeb65825fc054b4bd06 # use pre-built to bootstrap 
          name: app-inference
