---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: objectdetect-release010-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: objectdetect-release010-test 
  name: objectdetect-release010-test
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi