apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-objectdetect-release010-test-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-objectdetect-release010-test-gitops
    spec:  
      serviceAccountName: objectdetect-release010-test-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=objectdetect-release010-test-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/objectdetect-release010-test-notebook -- git clone https://github.com/jdubrick-ai/objectdetect-release010-test
      restartPolicy: Never